### ISSUE TITLE
Terminal window size doesn't update using ioctl.

### ISSUE THREAD

**Issue by TimonPost** [eminence/terminal-size#11] opened 2018-09-22 19:45 UTC
We can change the terminal size like the following two ways:

1. Using ANSI escape code: 

``` 
println!("\x1B[8;{},{}t", 40, 40)
```

2. Using the call to [ioctl()](http://man7.org/linux/man-pages/man2/ioctl_tty.2.html)
```
/// Get the current terminal size.
pub fn terminal_size() -> (u16, u16) {
    // http://rosettacode.org/wiki/Terminal_control/Dimensions#Library:_BSD_libc
    let us = UnixSize {
        rows: 0,
        cols: 0,
        ws_xpixel: 0,
        ws_ypixel: 0,
    };
    let r = unsafe { ioctl(STDOUT_FILENO, TIOCGWINSZ, &us) };
    if r == 0 {
        // because crossterm works starts counting at 0 and unix terminal starts at cell 1 you have subtract one to get 0-based results.
        (us.cols - 1, us.rows - 1)
    } else {
        (0, 0)
    }
}
```

**Problem**

If I set the terminal size with `ANSI escape code` and call directly the `ioctl(STDOUT_FILENO, TIOCGWINSZ, &mut winsize); ` after it to get the new terminal dimensions, the dimensions gotten back are not the same as we have set the terminal size to and will be instead the old dimentions before resizing. However, when running the application again we'll get the new (right) dimensions from the terminal.

The weird thing is that when adding `thread::sleep()` between the function calls to set and get the terminal size. We will get the new (right)dimensions back from `ioctl`

**Steps to reproduce:**

```
use crossterm::terminal::Terminal;
use std::{thread,time};

fn main()
{
    let screen = Screen::new(false);
    let terminal = Terminal::new(&screen.stdout);

    // get terminal size
    let (x, y) = terminal.terminal_size();

    // set size to 30, 50
    terminal.set_size(30,50);

    // if we uncomment the line below the code will work perfectly fine and we will get the new dimensions.
    // if we comment the line below the terminal dimensions gotten from terminal_size() are equal to the old dimensions. 
    
    // thread::sleep(time::Duration::from_millis(20));

    // get new dimensions
    let (x_new, y_new) = terminal.terminal_size();

    println!("old width: {} old height: {}", x, y);
    println!("new width: {} new height: {}", x_new, y_new);
}
```

To try the above code just comment and uncomment the code and see the result yourself.

I have found a [StackOverflow ](https://stackoverflow.com/questions/48568875/terminal-window-size-doesnt-update-using-ioctl) post that could be useful please take a look.

**Comment by eminence** [comment] 2018-09-26 00:32
Hi!  Thanks for the details report.   I'm able to reproduce the issue with your example.    Note that I can reproduce this on the command line as well, with this simple case:

    $ stty size; printf '\x1b[8;40;40t'; stty size

And as in your example, if I add a `sleep 0.1` after the printf, the second `stty` call will return the correct value.  I'm not really sure what to do here.   The StackOverflow post indicates that even a flush or or tcdrain isn't guaranteed to help.

**Comment by TimonPost** [comment] 2018-09-26 06:03
Fun thing is I forgot to say is that when using ioctl to set and get terminal size it would be updated.

**Comment by TimonPost** [comment] 2018-09-26 07:14
Lol I am the author of crossterm I accidentally made this issue at your crate but originally I wanted to crate this issue for my own crate. But nice you have that problem to so maybe we can work together on it ;)

**Comment by eminence** [comment] 2018-09-27 00:41
hah!  Ok, well it was good to learn about this issue, and it's good to have it documented in this repo in case anyone runs into it.  I'm also going to subscribe to the issue in your project, but since I'm not sure if anything needs to be done in the `terminal-size` repo, I'll close this issue for now.  Thanks!

**Closed by eminence** 2018-09-27 00:41 UTC
