### ISSUE TITLE
Fails to build for target s390x-unknown-linux-musl

### ISSUE THREAD

**Issue by OTLabs** [eminence/terminal-size#38] opened 2022-08-14 23:14 UTC
```
[361]error[E0277]: the trait bound `u64: From<i32>` is not satisfied
[362](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L362)  --> /home/buildozer/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/terminal_size-0.1.17/src/unix.rs:31:23
[363](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L363)   |
[364](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L364)31 |     if unsafe { ioctl(fd, TIOCGWINSZ.into(), &mut winsize) } == -1 {
[365](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L365)   |                 ----- ^^ the trait `From<i32>` is not implemented for `u64`
[366](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L366)   |                 |
[367](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L367)   |                 required by a bound introduced by this call
[368](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L368)   |
[369](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L369)   = help: the following other types implement trait `From<T>`:
[370](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L370)             <f32 as From<i16>>
[371](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L371)             <f32 as From<i8>>
[372](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L372)             <f32 as From<u16>>
[373](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L373)             <f32 as From<u8>>
[374](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L374)             <f64 as From<f32>>
[375](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L375)             <f64 as From<i16>>
[376](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L376)             <f64 as From<i32>>
[377](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L377)             <f64 as From<i8>>
[378](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L378)           and 67 others
[379](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L379)   = note: required because of the requirements on the impl of `Into<u64>` for `i32`
```
https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/802217#L361

**Comment by eminence** [comment] 2022-08-15 03:39
Thanks for the report.  Unfortunately I'm having a hard time reproducing this.  My rustup doesn't access to a `s390x-unknown-linux-musl` target; I only have `s390x-unknown-linux-gnu` target.   I do have some musl non-s390x targets available, and I tried a few of them, and none had this problem.

If you have easy access to a `s390x-unknown-linux-musl` target, can you try to build terminal-size v0.2.1?  That new version uses rustix, not libc, which changes the particular line that is failing.  If that works, then I can try to update rav1e and its deptree to use v0.2

**Comment by OTLabs** [comment] 2022-08-15 04:45
I would quite appreciate if you can try to update rav1e and its deptree to use v0.2.1.

**Comment by eminence** [comment] 2022-08-20 21:28
In order to update rav1e to terminal-size v0.2.1, I think all we need is a new release of clap.  (The latest clap release uses v0.1.17, but the master branch is using v0.2.1).  Since rav1e doesn't have a Cargo.toml, they already use the latest version of clap by default.

**Comment by tesuji** [comment] 2023-03-06 03:05
https://github.com/rust-lang/libc/pull/2615 should fix the
wrong type for ioctl on musl.

@OTLabs could you try again with newest libc crate version (e.g. 0.2.139)?

**Comment by OTLabs** [comment] 2023-03-07 03:02
Sure! Thank you! Giving it a try at https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44836 but get a new error...

**Comment by faptc** [comment] 2023-03-07 09:15
The build fails because cargo cannot download arbitrary package.
In your config, cargo fetch received --target flag but cargo build
didn't. Maybe that's what the problem is.

**Comment by OTLabs** [comment] 2023-03-08 04:10
The s390x binary was successfully build! Thank you!

**Comment by eminence** [comment] 2023-03-08 04:36
Thank you very much @tesuji and @faptc for your input here.  I'm going to close this issue as "solved" now

**Closed by eminence** 2023-03-08 04:36 UTC
Labels: help wanted
